Repository autonomys/auto-sdk, pull requests merged in 2024-11, with the labels that each got.

#144 Update pkg name and added encryption & compression logic
  .vscode/auto.code-workspace
  README.md
  packages/auto-dag-data/LICENSE
  packages/auto-dag-data/README.md
  packages/auto-dag-data/jest.config.ts
  packages/auto-dag-data/package.json
  packages/auto-dag-data/src/cid/index.ts
  packages/auto-dag-data/src/compression/index.ts
  packages/auto-dag-data/src/compression/types.ts
  packages/auto-dag-data/src/encryption/index.ts
  packages/auto-dag-data/src/encryption/types.ts
  packages/auto-dag-data/src/index.ts
  packages/auto-dag-data/src/ipld/builders.ts
  packages/auto-dag-data/src/ipld/chunker.ts
  packages/auto-dag-data/src/ipld/index.ts
  packages/auto-dag-data/src/ipld/nodes.ts
  packages/auto-dag-data/src/ipld/utils.ts
  packages/auto-dag-data/src/metadata/index.ts
  packages/auto-dag-data/src/metadata/offchain/base.ts
  packages/auto-dag-data/src/metadata/offchain/file.ts
  packages/auto-dag-data/src/metadata/offchain/folder.ts
  packages/auto-dag-data/src/metadata/offchain/index.ts
  packages/auto-dag-data/src/metadata/onchain/index.ts
  packages/auto-dag-data/src/metadata/onchain/protobuf/OnchainMetadata.proto
  packages/auto-dag-data/src/metadata/onchain/protobuf/OnchainMetadata.ts
  packages/auto-dag-data/src/metadata/onchain/utils.ts
  packages/auto-dag-data/src/utils/async.ts
  packages/auto-dag-data/src/utils/index.ts
  packages/auto-dag-data/src/utils/types.ts
  packages/auto-dag-data/tests/chunker.spec.ts
  packages/auto-dag-data/tests/cid.spec.ts
  packages/auto-dag-data/tests/compression.spec.ts
  packages/auto-dag-data/tests/encryption.spec.ts
  packages/auto-dag-data/tests/nodes.spec.ts
  packages/auto-dag-data/tsconfig.json
  yarn.lock
Labels: Review effort [1-5]: 4

#145 Add auto-drive package for managing API interaction
  packages/auto-drive/README.md
  packages/auto-drive/package.json
  packages/auto-drive/src/api/calls/download.ts
  packages/auto-drive/src/api/calls/index.ts
  packages/auto-drive/src/api/calls/read.ts
  packages/auto-drive/src/api/calls/upload.ts
  packages/auto-drive/src/api/calls/write.ts
  packages/auto-drive/src/api/connection.ts
  packages/auto-drive/src/api/index.ts
  packages/auto-drive/src/api/models/folderTree.ts
  packages/auto-drive/src/api/models/index.ts
  packages/auto-drive/src/api/models/objects.ts
  packages/auto-drive/src/api/models/uploads.ts
  packages/auto-drive/src/api/wrappers.ts
  packages/auto-drive/src/index.ts
  packages/auto-drive/src/utils/async.ts
  packages/auto-drive/src/utils/folder.ts
  packages/auto-drive/src/utils/index.ts
  packages/auto-drive/src/utils/stream.ts
  packages/auto-drive/src/utils/types.ts
  packages/auto-drive/tsconfig.json
  yarn.lock
Labels: Review effort [1-5]: 5

#147 Version 0.8.2
  lerna.json
  packages/auto-consensus/package.json
  packages/auto-dag-data/package.json
  packages/auto-drive/package.json
  packages/auto-id/package.json
  packages/auto-utils/package.json
  packages/auto-xdm/package.json
  yarn.lock
Labels: Review effort [1-5]: 2

#149 Publish 1.0.0
  .vscode/auto.code-workspace
  lerna.json
  packages/auto-consensus/package.json
  packages/auto-dag-data/package.json
  packages/auto-drive/package.json
  packages/auto-id/package.json
  packages/auto-utils/package.json
  packages/auto-xdm/package.json
  yarn.lock
Labels: Review effort [1-5]: 2

#150 Change rpc for autonomys labs rpcs
  packages/auto-utils/src/constants/network.ts
Labels: Review effort [1-5]: 1

#151 Publish 1.0.1
  lerna.json
  packages/auto-consensus/package.json
  packages/auto-dag-data/package.json
  packages/auto-drive/package.json
  packages/auto-id/package.json
  packages/auto-utils/package.json
  packages/auto-xdm/package.json
  yarn.lock
Labels: Review effort [1-5]: 2

#155 Remove rpc-1 (deprecated) from gemini-3h
  packages/auto-utils/src/constants/network.ts
Labels: Review effort [1-5]: 1

#156 Publish 1.0.2
  lerna.json
  packages/auto-consensus/package.json
  packages/auto-dag-data/package.json
  packages/auto-drive/package.json
  packages/auto-id/package.json
  packages/auto-utils/package.json
  packages/auto-xdm/package.json
  yarn.lock
Labels: Review effort [1-5]: 2

#154 Revert update importing ts extensions
  packages/auto-drive/src/api/calls/download.ts
  packages/auto-drive/src/api/calls/index.ts
  packages/auto-drive/src/api/calls/read.ts
  packages/auto-drive/src/api/calls/upload.ts
  packages/auto-drive/src/api/calls/write.ts
  packages/auto-drive/src/api/index.ts
  packages/auto-drive/src/api/models/index.ts
  packages/auto-drive/src/api/models/uploads.ts
  packages/auto-drive/src/api/wrappers.ts
  packages/auto-drive/src/index.ts
  packages/auto-drive/src/utils/index.ts
  packages/auto-drive/tsconfig.json
Labels: Review effort [1-5]: 2

#157 Upload folder & upload file returns head CID
  packages/auto-dag-data/src/ipld/utils.ts
  packages/auto-drive/src/api/calls/upload.ts
  packages/auto-drive/src/api/models/uploads.ts
  packages/auto-drive/src/api/wrappers.ts
Labels: Review effort [1-5]: 3

#158 Enable oauth authentication in api connection
  packages/auto-drive/src/api/connection.ts
Labels: Review effort [1-5]: 3

#159 v1.0.4 + Prepublishing script
  lerna.json
  package.json
  packages/auto-consensus/package.json
  packages/auto-dag-data/package.json
  packages/auto-drive/package.json
  packages/auto-id/package.json
  packages/auto-utils/package.json
  packages/auto-xdm/package.json
  yarn.lock
Labels: Review effort [1-5]: 2

#162 Fix encryption bug
  packages/auto-dag-data/src/encryption/index.ts
  packages/auto-dag-data/tests/encryption.spec.ts
Labels: Review effort [1-5]: 3

#161 Update auto-drive wrapper functions
  packages/auto-dag-data/package.json
  packages/auto-dag-data/src/cid/index.ts
  packages/auto-drive/package.json
  packages/auto-drive/src/api/calls/upload.ts
  packages/auto-drive/src/api/connection.ts
  packages/auto-drive/src/api/models/file.ts
  packages/auto-drive/src/api/models/folderTree.ts
  packages/auto-drive/src/api/models/uploads.ts
  packages/auto-drive/src/api/wrappers.ts
  packages/auto-drive/src/utils/async.ts
  packages/auto-drive/src/utils/misc.ts
  packages/auto-drive/src/utils/observable.ts
  yarn.lock
Labels: Review effort [1-5]: 4

#163 Update auto-drive wrapper functions
  packages/auto-dag-data/package.json
  packages/auto-dag-data/src/cid/index.ts
  packages/auto-drive/package.json
  packages/auto-drive/src/api/calls/upload.ts
  packages/auto-drive/src/api/connection.ts
  packages/auto-drive/src/api/models/file.ts
  packages/auto-drive/src/api/models/folderTree.ts
  packages/auto-drive/src/api/models/uploads.ts
  packages/auto-drive/src/api/wrappers.ts
  packages/auto-drive/src/utils/async.ts
  packages/auto-drive/src/utils/misc.ts
  packages/auto-drive/src/utils/observable.ts
  yarn.lock
Labels: Review effort [1-5]: 4

#164 Bumped version to 1.0.5
  lerna.json
  packages/auto-consensus/package.json
  packages/auto-dag-data/package.json
  packages/auto-drive/package.json
  packages/auto-id/package.json
  packages/auto-utils/package.json
  packages/auto-xdm/package.json
  yarn.lock
Labels: Review effort [1-5]: 2

#165 Add minimum node version requirement
  packages/auto-dag-data/package.json
  packages/auto-drive/package.json
Labels: Review effort [1-5]: 1

#166 Fix File not supported in nodejs
  packages/auto-drive/src/api/wrappers.ts
Labels: Review effort [1-5]: 3

#168 Adding space formatter utils functions
  packages/auto-consensus/src/utils/format.ts
  packages/auto-consensus/src/utils/index.ts
Labels: Review effort [1-5]: 2

#169 Publish v1.0.6
  lerna.json
  packages/auto-consensus/package.json
  packages/auto-dag-data/package.json
  packages/auto-drive/package.json
  packages/auto-id/package.json
  packages/auto-utils/package.json
  packages/auto-xdm/package.json
  yarn.lock
Labels: Review effort [1-5]: 2

#170 Change Subscan URL
  packages/auto-utils/src/constants/network.ts
Labels: Review effort [1-5]: 1

#174 Add @peculiar/webcrypto to auto-dag-data
  packages/auto-dag-data/package.json
  yarn.lock
Labels: Review effort [1-5]: 1, Bug fix

#172 Unify README's formatting
  .github/workflows/build.yaml
  README.md
  packages/auto-dag-data/README.md
  packages/auto-drive/README.md
  packages/auto-utils/README.md
Labels: enhancement, Review effort [1-5]: 1

#171 update: chunk size limitation
  packages/auto-dag-data/src/ipld/builders.ts
  packages/auto-dag-data/src/ipld/chunker.ts
  packages/auto-dag-data/src/ipld/nodes.ts
  packages/auto-dag-data/src/metadata/offchain/file.ts
  packages/auto-dag-data/src/metadata/offchain/folder.ts
  packages/auto-dag-data/src/metadata/onchain/protobuf/OnchainMetadata.proto
  packages/auto-dag-data/src/metadata/onchain/protobuf/OnchainMetadata.ts
  packages/auto-dag-data/src/utils/metadata.ts
  packages/auto-dag-data/tests/chunker.spec.ts
  packages/auto-dag-data/tests/nodes.spec.ts
Labels: Review effort [1-5]: 4

#167 Update doc for changes in wrappers
  packages/auto-dag-data/README.md
  packages/auto-drive/README.md
Labels: Review effort [1-5]: 4

#175 v1.0.8
  lerna.json
  packages/auto-consensus/package.json
  packages/auto-dag-data/package.json
  packages/auto-drive/package.json
  packages/auto-id/package.json
  packages/auto-utils/package.json
  packages/auto-xdm/package.json
  yarn.lock
Labels: Review effort [1-5]: 1

#177 Add more testing to `@autonomys/auto-dag-data`
  lerna.json
  packages/auto-consensus/package.json
  packages/auto-dag-data/jest.config.ts
  packages/auto-dag-data/package.json
  packages/auto-dag-data/src/compression/index.ts
  packages/auto-dag-data/src/encryption/index.ts
  packages/auto-dag-data/src/ipld/chunker.ts
  packages/auto-dag-data/src/ipld/nodes.ts
  packages/auto-dag-data/tests/chunker.spec.ts
  packages/auto-dag-data/tests/compression.spec.ts
  packages/auto-dag-data/tests/encryption.spec.ts
  packages/auto-dag-data/tests/fileRetrievability.spec.ts
  packages/auto-dag-data/tests/nodes.spec.ts
  packages/auto-dag-data/tests/offchainMetadata.spec.ts
  packages/auto-drive/package.json
  packages/auto-id/package.json
  packages/auto-utils/package.json
  packages/auto-xdm/package.json
  yarn.lock
Labels: Review effort [1-5]: 3

#179 Update @polkadot/api to 14.3.1
  packages/auto-utils/package.json
  yarn.lock
Labels: Review effort [1-5]: 1

#180 Publish 1.0.9
  lerna.json
  packages/auto-consensus/package.json
  packages/auto-dag-data/package.json
  packages/auto-drive/package.json
  packages/auto-id/package.json
  packages/auto-utils/package.json
  packages/auto-xdm/package.json
  yarn.lock
Labels: Review effort [1-5]: 2

#178 Improve network types
  examples/next/src/hooks/useNetwork.tsx
  packages/auto-utils/src/types/network.ts
Labels: Review effort [1-5]: 2

#182 Fix packages dedupe conflict
  packages/auto-utils/package.json
  packages/auto-xdm/package.json
  yarn.lock
Labels: Review effort [1-5]: 1

#183 Remove register operator proof of ownership
  examples/next/src/components/actions/register.tsx
  packages/auto-consensus/src/staking.ts
  packages/auto-consensus/src/types/staking.ts
Labels: Review effort [1-5]: 3
