Repository autonomys/auto-sdk, pull requests merged in 2024-09, with the labels that each got.

#103 feat: add auto-drive package
  packages/auto-drive/README.md
  packages/auto-drive/jest.config.ts
  packages/auto-drive/package.json
  packages/auto-drive/src/cid/index.ts
  packages/auto-drive/src/index.ts
  packages/auto-drive/src/ipld/chunker.ts
  packages/auto-drive/src/ipld/index.ts
  packages/auto-drive/src/ipld/nodes.ts
  packages/auto-drive/src/ipld/utils.ts
  packages/auto-drive/src/metadata/index.ts
  packages/auto-drive/src/metadata/offchain/base.ts
  packages/auto-drive/src/metadata/offchain/file.ts
  packages/auto-drive/src/metadata/offchain/folder.ts
  packages/auto-drive/src/metadata/offchain/index.ts
  packages/auto-drive/src/metadata/onchain/index.ts
  packages/auto-drive/src/metadata/onchain/protobuf/OnchainMetadata.proto
  packages/auto-drive/src/metadata/onchain/protobuf/OnchainMetadata.ts
  packages/auto-drive/src/metadata/onchain/utils.ts
  packages/auto-drive/tests/chunker.spec.ts
  packages/auto-drive/tests/cid.spec.ts
  packages/auto-drive/tests/nodes.spec.ts
  packages/auto-drive/tsconfig.json
  yarn.lock
Labels: documentation, enhancement, Review effort [1-5]: 3

#105 Bumped to 0.5.0
  examples/next/package-lock.json
  examples/next/package.json
  examples/node/package.json
  lerna.json
  packages/auto-consensus/package.json
  packages/auto-drive/package.json
  packages/auto-id/package.json
  packages/auto-utils/package.json
  packages/auto-xdm/package.json
  yarn.lock
Labels: enhancement, Review effort [1-5]: 1

#107 Fixed missing folder name in metadata
  packages/auto-drive/src/metadata/offchain/folder.ts
Labels: Review effort [1-5]: 2, bug_fix

#108 Version 0.5.2
  examples/next/package-lock.json
  examples/next/package.json
  examples/node/package.json
  lerna.json
  packages/auto-consensus/package.json
  packages/auto-drive/package.json
  packages/auto-id/package.json
  packages/auto-utils/package.json
  packages/auto-xdm/package.json
  yarn.lock
Labels: enhancement, Review effort [1-5]: 1

#110 Publish 0.6.1
  .vscode/auto.code-workspace
  examples/next/package-lock.json
  examples/next/package.json
  examples/node/package.json
  lerna.json
  packages/auto-consensus/package.json
  packages/auto-drive/package.json
  packages/auto-id/package.json
  packages/auto-utils/package.json
  packages/auto-xdm/package.json
  yarn.lock
Labels: enhancement, Review effort [1-5]: 2, Configuration changes
