Repository autonomys/auto-sdk, pull requests merged in 2024-10, with the labels that each got.

#112 Fix file chunks list creation
  packages/auto-drive/src/metadata/offchain/file.ts
Labels: Review effort [1-5]: 2, Bug fix

#113 v0.6.2
  lerna.json
  packages/auto-consensus/package.json
  packages/auto-drive/package.json
  packages/auto-id/package.json
  packages/auto-utils/package.json
  packages/auto-xdm/package.json
  yarn.lock
Labels: enhancement, Review effort [1-5]: 1

#114 Improve README's
  .github/images/autonomys-banner.webp
  CODE_OF_CONDUCT.md
  LICENSE
  README.md
  packages/auto-consensus/LICENSE
  packages/auto-consensus/README.md
  packages/auto-drive/LICENSE
  packages/auto-drive/README.md
  packages/auto-id/LICENSE
  packages/auto-id/README.md
  packages/auto-utils/LICENSE
  packages/auto-utils/README.md
Labels: documentation, Review effort [1-5]: 5

#115 Version 0.6.2 Git Head
  packages/auto-consensus/package.json
  packages/auto-drive/package.json
  packages/auto-id/package.json
  packages/auto-utils/package.json
  packages/auto-xdm/package.json
Labels: Review effort [1-5]: 1, other

#116 Publish 0.6.3
  lerna.json
  packages/auto-consensus/package.json
  packages/auto-drive/package.json
  packages/auto-id/package.json
  packages/auto-utils/package.json
  packages/auto-xdm/package.json
  yarn.lock
Labels: enhancement, Review effort [1-5]: 2

#117 Add metadata dag builder
  packages/auto-drive/README.md
  packages/auto-drive/src/ipld/builders.ts
  packages/auto-drive/src/ipld/chunker.ts
  packages/auto-drive/src/ipld/nodes.ts
  packages/auto-drive/src/metadata/onchain/protobuf/OnchainMetadata.proto
  packages/auto-drive/src/metadata/onchain/protobuf/OnchainMetadata.ts
  packages/auto-drive/tests/chunker.spec.ts
  packages/auto-drive/tests/nodes.spec.ts
Labels: enhancement, tests, Review effort [1-5]: 3

#118 Version 0.6.5
  lerna.json
  packages/auto-consensus/package.json
  packages/auto-drive/package.json
  packages/auto-id/package.json
  packages/auto-utils/package.json
  packages/auto-xdm/package.json
  yarn.lock
Labels: enhancement, Review effort [1-5]: 2

#119 Add some basic string utility functions
  packages/auto-utils/src/index.ts
  packages/auto-utils/src/string.ts
Labels: enhancement, Review effort [1-5]: 2

#120 Fix spacePledge return type
  packages/auto-consensus/src/info.ts
Labels: enhancement, Review effort [1-5]: 2, Bug fix

#121 Fix type of nonce in account
  packages/auto-consensus/src/account.ts
  packages/auto-consensus/src/types/account.ts
  packages/auto-consensus/src/utils/parse.ts
Labels: enhancement, Review effort [1-5]: 2, Bug fix

#123 Publish 0.6.6
  packages/auto-consensus/package.json
  packages/auto-drive/package.json
  packages/auto-id/package.json
  packages/auto-utils/package.json
  packages/auto-xdm/package.json
Labels: Review effort [1-5]: 1, other

#125 Update space pledge logic
  packages/auto-consensus/src/info.ts
Labels: enhancement, Review effort [1-5]: 3

#126 Publish 0.6.7
  lerna.json
  packages/auto-consensus/package.json
  packages/auto-drive/package.json
  packages/auto-id/package.json
  packages/auto-utils/package.json
  packages/auto-xdm/package.json
  yarn.lock
Labels: enhancement, Review effort [1-5]: 1

#128 Update polkadot dependencies and run dedupe
  packages/auto-utils/package.json
  yarn.lock
Labels: enhancement, dependencies, Review effort [1-5]: 1

#129 Delete .github/workflows/publish.yaml
  .github/workflows/publish.yaml
Labels: Review effort [1-5]: 1, Configuration changes

#127 Fix blockchain size function
  packages/auto-consensus/src/info.ts
  packages/auto-consensus/src/types/block.ts
Labels: enhancement, Review effort [1-5]: 3, bug_fix

#130 Publish 0.6.8
  lerna.json
  packages/auto-consensus/package.json
  packages/auto-drive/package.json
  packages/auto-id/package.json
  packages/auto-utils/package.json
  packages/auto-xdm/package.json
  yarn.lock
Labels: Review effort [1-5]: 2

#132 Fix spacePledge typo -> spacePledged
  packages/auto-consensus/src/info.ts
Labels: Review effort [1-5]: 2

#133 Add support for Taurus testnet
  packages/auto-utils/src/constants/network.ts
  packages/auto-utils/src/constants/token.ts
Labels: Review effort [1-5]: 2

#134 Publish v0.7.0
  lerna.json
  packages/auto-consensus/package.json
  packages/auto-drive/package.json
  packages/auto-id/package.json
  packages/auto-utils/package.json
  packages/auto-xdm/package.json
  yarn.lock
Labels: Review effort [1-5]: 2

#137 Fix taurus url and publish 0.7.1
  lerna.json
  packages/auto-consensus/package.json
  packages/auto-drive/package.json
  packages/auto-id/package.json
  packages/auto-utils/package.json
  packages/auto-xdm/package.json
  yarn.lock
Labels: Review effort [1-5]: 2

#131 Enable Processing of Large Files to IPLD Format
  packages/auto-drive/package.json
  packages/auto-drive/src/cid/index.ts
  packages/auto-drive/src/ipld/builders.ts
  packages/auto-drive/src/ipld/chunker.ts
  packages/auto-drive/src/ipld/index.ts
  packages/auto-drive/src/ipld/nodes.ts
  packages/auto-drive/src/ipld/utils.ts
  packages/auto-drive/src/metadata/offchain/file.ts
  packages/auto-drive/src/metadata/offchain/folder.ts
  packages/auto-drive/src/metadata/onchain/utils.ts
  packages/auto-drive/tests/chunker.spec.ts
  packages/auto-drive/tests/cid.spec.ts
  packages/auto-drive/tests/nodes.spec.ts
  yarn.lock
Labels: Review effort [1-5]: 3

#141 Change taurus rpcs urls
  packages/auto-utils/src/constants/network.ts
Labels: Review effort [1-5]: 2

#142 Publish 0.7.3
  lerna.json
  packages/auto-consensus/package.json
  packages/auto-drive/package.json
  packages/auto-id/package.json
  packages/auto-utils/package.json
  packages/auto-xdm/package.json
  yarn.lock
Labels: Review effort [1-5]: 2

#140 Added upload options (encryption/compression) for head nodes
  packages/auto-drive/src/ipld/builders.ts
  packages/auto-drive/src/ipld/chunker.ts
  packages/auto-drive/src/ipld/nodes.ts
  packages/auto-drive/src/metadata/offchain/file.ts
  packages/auto-drive/src/metadata/offchain/folder.ts
  packages/auto-drive/src/metadata/onchain/protobuf/OnchainMetadata.proto
  packages/auto-drive/src/metadata/onchain/protobuf/OnchainMetadata.ts
Labels: Review effort [1-5]: 4

#143 Version 0.7.4
  lerna.json
  packages/auto-consensus/package.json
  packages/auto-drive/package.json
  packages/auto-id/package.json
  packages/auto-utils/package.json
  packages/auto-xdm/package.json
  yarn.lock
Labels: Review effort [1-5]: 2
