Repository autonomys/auto-sdk, pull requests merged in 2024-07, with the labels that each got.

#69 Create the auto xdm basic package
  .vscode/auto.code-workspace
  packages/auto-xdm/README.md
  packages/auto-xdm/jest.config.js
  packages/auto-xdm/package.json
  packages/auto-xdm/src/transfer.ts
  packages/auto-xdm/tsconfig.json
  yarn.lock
Labels: auto-xdm

#68 Add function to return last blockNumber, blockHash, and more flexible functions
  packages/auto-consensus/__test__/info.test.ts
  packages/auto-consensus/src/info.ts
  packages/auto-consensus/src/utils/query.ts
Labels: auto-consensus

#77 Move utils around
  .yarn/install-state.gz
  examples/next/src/hooks/useTx.tsx
  packages/auto-consensus/__test__/helpers/tx.ts
  packages/auto-consensus/__test__/staking.test.ts
  packages/auto-consensus/src/types/events.ts
  packages/auto-consensus/src/types/index.ts
  packages/auto-consensus/src/utils/index.ts
  packages/auto-consensus/src/utils/sudo.ts
  packages/auto-utils/src/types/event.ts
  packages/auto-utils/src/types/index.ts
  packages/auto-utils/src/types/transaction.ts
  packages/auto-utils/src/utils/detectTxSuccess.ts
  packages/auto-utils/src/utils/events.ts
  packages/auto-utils/src/utils/index.ts
  packages/auto-utils/src/utils/signAndSendTx.ts
  packages/auto-utils/src/utils/validateEvents.ts
Labels: enhancement, tests, Review effort [1-5]: 3

#78 Add more domains and staking related read functions
  packages/auto-consensus/src/domain.ts
  packages/auto-consensus/src/index.ts
  packages/auto-consensus/src/staking.ts
  packages/auto-consensus/src/types/domain.ts
  packages/auto-consensus/src/types/index.ts
  packages/auto-consensus/src/types/staking.ts
  packages/auto-consensus/src/utils/index.ts
  packages/auto-consensus/src/utils/parse.ts
Labels: documentation, enhancement, Review effort [1-5]: 3

#83 Add devnet in network list
  .vscode/auto.code-workspace
  .vscode/settings.json
  .yarn/install-state.gz
  lerna.json
  packages/auto-consensus/package.json
  packages/auto-id/package.json
  packages/auto-utils/package.json
  packages/auto-utils/src/constants/network.ts
  packages/auto-xdm/package.json
  yarn.lock
Labels: enhancement, Review effort [1-5]: 2, Configuration changes

#80 Improve typing to support api.at
  packages/auto-consensus/src/balances.ts
  packages/auto-consensus/src/domain.ts
  packages/auto-consensus/src/info.ts
  packages/auto-consensus/src/staking.ts
  packages/auto-utils/src/types/wallet.ts
Labels: enhancement, Review effort [1-5]: 2

#84 fix domains details
  .vscode/auto.code-workspace
  .vscode/settings.json
  packages/auto-utils/src/constants/network.ts
Labels: Review effort [1-5]: 2, Bug fix

#79 Publishing 0.1.5-0.1.6
  .yarn/install-state.gz
  lerna.json
  packages/auto-consensus/package.json
  packages/auto-consensus/src/balances.ts
  packages/auto-consensus/src/domain.ts
  packages/auto-consensus/src/info.ts
  packages/auto-consensus/src/staking.ts
  packages/auto-id/package.json
  packages/auto-utils/package.json
  packages/auto-utils/src/types/wallet.ts
  packages/auto-xdm/package.json
  yarn.lock
Labels: enhancement, dependencies, Review effort [1-5]: 1

#75 Add more features to Auto ID
  .gitignore
  .yarn/install-state.gz
  examples/auto-id/.env.local
  examples/auto-id/README.md
  examples/auto-id/package.json
  examples/auto-id/src/registerAutoId.ts
  examples/auto-id/tsconfig.json
  examples/node/.env.local
  examples/node/README.md
  examples/node/package.json
  examples/node/res/private.issuer.pem
  examples/node/res/private.leaf.pem
  examples/node/src/auto-id/deactivate.ts
  examples/node/src/auto-id/register.ts
  examples/node/src/auto-id/renew-leaf.ts
  examples/node/src/auto-id/renew-self.ts
  examples/node/src/auto-id/revoke-leaf.ts
  examples/node/src/auto-id/revoke-self.ts
  examples/node/src/auto-id/utils.ts
  examples/node/src/auto-id/view-cert.ts
  examples/node/src/auto-id/view-revoked-certs.ts
  packages/auto-id/res/private.issuer.pem
  packages/auto-id/res/private.leaf.pem
  packages/auto-id/src/certificateManager.ts
  packages/auto-id/src/keyManagement.ts
  packages/auto-id/src/registry.ts
  packages/auto-id/src/utils.ts
  packages/auto-id/tests/certificateManager.test.ts
  packages/auto-id/tests/keyManagement.test.ts
  packages/auto-utils/src/utils/signAndSendTx.ts
  yarn.lock
Labels: enhancement, tests, Review effort [1-5]: 4

#85 Improve deposit and withdrawals parsing
  packages/auto-consensus/src/types/staking.ts
  packages/auto-consensus/src/utils/parse.ts
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#90 AutoID Refactor - Part 2
  examples/node/package.json
  examples/node/src/auto-id/auto-id-extrinsics.ts
  examples/node/src/auto-id/deactivate.ts
  examples/node/src/auto-id/renew-leaf.ts
  examples/node/src/auto-id/renew-self.ts
  examples/node/src/auto-id/renew.ts
  examples/node/src/auto-id/revoke-leaf.ts
  examples/node/src/auto-id/revoke-self.ts
  packages/auto-id/src/index.ts
  packages/auto-id/src/misc-utils.ts
  packages/auto-id/src/registry.ts
  packages/auto-id/src/types/index.ts
  packages/auto-id/src/types/registry.ts
  packages/auto-id/src/utils.ts
  packages/auto-id/src/utils/index.ts
  packages/auto-id/src/utils/signature.ts
  packages/auto-id/tests/utils.test.ts
Labels: enhancement, tests, Review effort [1-5]: 3
