Repository autonomys/auto-sdk, pull requests merged in 2024-08, with the labels that each got.

#91 Simplify network name and fix urls
  examples/next/src/hooks/useNetwork.tsx
  examples/node/src/utils/setup.ts
  lerna.json
  packages/auto-consensus/__test__/helpers/setup.ts
  packages/auto-consensus/package.json
  packages/auto-id/package.json
  packages/auto-utils/__test__/network.test.ts
  packages/auto-utils/__test__/wallet.test.ts
  packages/auto-utils/package.json
  packages/auto-utils/src/constants/network.ts
  packages/auto-xdm/package.json
  yarn.lock
Labels: enhancement, Review effort [1-5]: 2, Bug fix

#93 Add default token details
  packages/auto-utils/src/constants/network.ts
  packages/auto-utils/src/constants/token.ts
  packages/auto-utils/src/types/index.ts
  packages/auto-utils/src/types/network.ts
  packages/auto-utils/src/types/token.ts
Labels: enhancement, Review effort [1-5]: 1

#92 Split domains from network
  packages/auto-utils/src/constants/domain.ts
  packages/auto-utils/src/constants/index.ts
  packages/auto-utils/src/constants/network.ts
  packages/auto-utils/src/network.ts
  packages/auto-utils/src/types/domain.ts
  packages/auto-utils/src/types/network.ts
Labels: enhancement, Review effort [1-5]: 2

#95 refactor: remove dependency with crypto module
  packages/auto-id/package.json
  packages/auto-id/src/keyManagement.ts
  packages/auto-id/tests/certificateManager.test.ts
  packages/auto-id/tests/keyManagement.test.ts
  yarn.lock
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#96 fix: crypto module not correctly setup in browser
  packages/auto-id/src/certificateManager.ts
  packages/auto-id/src/keyManagement.ts
  packages/auto-id/src/utils/index.ts
  packages/auto-id/src/utils/pem.ts
  packages/auto-id/tests/keyManagement.test.ts
Labels: Review effort [1-5]: 2, Bug fix

#98 Pumped version to 0.3.0
  lerna.json
  packages/auto-consensus/package.json
  packages/auto-id/package.json
  packages/auto-utils/package.json
  packages/auto-xdm/package.json
  yarn.lock
Labels: enhancement, dependencies, Review effort [1-5]: 1

#102 Auto-SDK Version Pumped To 0.4.0
  lerna.json
  packages/auto-consensus/package.json
  packages/auto-id/package.json
  packages/auto-utils/package.json
  packages/auto-xdm/package.json
  yarn.lock
Labels: enhancement, Review effort [1-5]: 1
